// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "manawave-season-zero-1.proto" (syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum ClanCardDefs
 */
export enum ClanCardDefs {
    /**
     * @generated from protobuf enum value: ClanCard_NotSet = 0;
     */
    ClanCard_NotSet = 0,
    /**
     * @generated from protobuf enum value: ClanOfSacrifice = 1;
     */
    ClanOfSacrifice = 1,
    /**
     * @generated from protobuf enum value: ClanOfLife = 2;
     */
    ClanOfLife = 2,
    /**
     * @generated from protobuf enum value: ClanOfDiversity = 3;
     */
    ClanOfDiversity = 3
}
/**
 * @generated from protobuf enum TotemDefs
 */
export enum TotemDefs {
    /**
     * @generated from protobuf enum value: Totem_NotSet = 0;
     */
    Totem_NotSet = 0,
    /**
     * @generated from protobuf enum value: Totem_Ox = 1;
     */
    Totem_Ox = 1,
    /**
     * @generated from protobuf enum value: Totem_Spirits = 2;
     */
    Totem_Spirits = 2,
    /**
     * @generated from protobuf enum value: Totem_Tiger = 3;
     */
    Totem_Tiger = 3
}
/**
 * @generated from protobuf enum MonumentCardDefs
 */
export enum MonumentCardDefs {
    /**
     * @generated from protobuf enum value: MonumentCard_NotSet = 0;
     */
    MonumentCard_NotSet = 0,
    /**
     * @generated from protobuf enum value: MonumentOfLife = 1;
     */
    MonumentOfLife = 1,
    /**
     * @generated from protobuf enum value: MonumentOfSacrifice = 2;
     */
    MonumentOfSacrifice = 2,
    /**
     * @generated from protobuf enum value: MonumentOfDiversty = 3;
     */
    MonumentOfDiversty = 3,
    /**
     * @generated from protobuf enum value: MonumentOfJustice = 4;
     */
    MonumentOfJustice = 4,
    /**
     * @generated from protobuf enum value: MonumentOfTranquility = 5;
     */
    MonumentOfTranquility = 5,
    /**
     * @generated from protobuf enum value: MonumentOfMagic = 6;
     */
    MonumentOfMagic = 6,
    /**
     * @generated from protobuf enum value: MonumentOfNature = 7;
     */
    MonumentOfNature = 7,
    /**
     * @generated from protobuf enum value: MonumentOfWar = 8;
     */
    MonumentOfWar = 8,
    /**
     * @generated from protobuf enum value: MonumentOfPeace = 9;
     */
    MonumentOfPeace = 9
}
