// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "manawave-season-flavor-1.proto" (syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum SeasonFlavor1ClanCardDefs
 */
export enum SeasonFlavor1ClanCardDefs {
    /**
     * @generated from protobuf enum value: SeasonFlavor1ClanCard_NotSet = 0;
     */
    SeasonFlavor1ClanCard_NotSet = 0,
    /**
     * @generated from protobuf enum value: SeasonFlavor1ClanOfAttack = 1;
     */
    SeasonFlavor1ClanOfAttack = 1,
    /**
     * @generated from protobuf enum value: SeasonFlavor1ClanOfDefense = 2;
     */
    SeasonFlavor1ClanOfDefense = 2,
    /**
     * @generated from protobuf enum value: SeasonFlavor1ClanOfMagic = 3;
     */
    SeasonFlavor1ClanOfMagic = 3
}
/**
 * @generated from protobuf enum SeasonFlavor1TotemDefs
 */
export enum SeasonFlavor1TotemDefs {
    /**
     * @generated from protobuf enum value: SeasonFlavor1Totem_NotSet = 0;
     */
    SeasonFlavor1Totem_NotSet = 0,
    /**
     * @generated from protobuf enum value: SeasonFlavor1Totem_Attack = 1;
     */
    SeasonFlavor1Totem_Attack = 1,
    /**
     * @generated from protobuf enum value: SeasonFlavor1Totem_Defense = 2;
     */
    SeasonFlavor1Totem_Defense = 2,
    /**
     * @generated from protobuf enum value: SeasonFlavor1Totem_Magic = 3;
     */
    SeasonFlavor1Totem_Magic = 3
}
/**
 * @generated from protobuf enum SeasonFlavor1MonumentCardDefs
 */
export enum SeasonFlavor1MonumentCardDefs {
    /**
     * @generated from protobuf enum value: SeasonFlavor1MonumentCard_NotSet = 0;
     */
    SeasonFlavor1MonumentCard_NotSet = 0,
    /**
     * @generated from protobuf enum value: ManalithCliffs = 1;
     */
    ManalithCliffs = 1,
    /**
     * @generated from protobuf enum value: RuinsOfErkul = 2;
     */
    RuinsOfErkul = 2,
    /**
     * @generated from protobuf enum value: SeaOfLyrtif = 3;
     */
    SeaOfLyrtif = 3,
    /**
     * @generated from protobuf enum value: BirthplaceOfGenghis = 4;
     */
    BirthplaceOfGenghis = 4,
    /**
     * @generated from protobuf enum value: TombOfGenghis = 5;
     */
    TombOfGenghis = 5,
    /**
     * @generated from protobuf enum value: GravepitsOfLeruk = 6;
     */
    GravepitsOfLeruk = 6,
    /**
     * @generated from protobuf enum value: FieldsOfLeruk = 7;
     */
    FieldsOfLeruk = 7,
    /**
     * @generated from protobuf enum value: PeaksOfTheoden = 8;
     */
    PeaksOfTheoden = 8,
    /**
     * @generated from protobuf enum value: PlainsOfTheoden = 9;
     */
    PlainsOfTheoden = 9
}
/**
 * @generated from protobuf enum SeasonFlavor1FamilyCardDefs
 */
export enum SeasonFlavor1FamilyCardDefs {
    /**
     * @generated from protobuf enum value: SeasonFlavor1FamilyCard_NotSet = 0;
     */
    SeasonFlavor1FamilyCard_NotSet = 0,
    /**
     * @generated from protobuf enum value: SeasonFlavor1AttackFamilyCards = 10;
     */
    SeasonFlavor1AttackFamilyCards = 10,
    /**
     * @generated from protobuf enum value: SeasonFlavor1Attackers1 = 11;
     */
    SeasonFlavor1Attackers1 = 11,
    /**
     * @generated from protobuf enum value: SeasonFlavor1Attackers2 = 12;
     */
    SeasonFlavor1Attackers2 = 12,
    /**
     * @generated from protobuf enum value: SeasonFlavor1Attackers3 = 13;
     */
    SeasonFlavor1Attackers3 = 13,
    /**
     * @generated from protobuf enum value: SeasonFlavor1Attackers4 = 14;
     */
    SeasonFlavor1Attackers4 = 14,
    /**
     * @generated from protobuf enum value: SeasonFlavor1Attackers5 = 15;
     */
    SeasonFlavor1Attackers5 = 15,
    /**
     * @generated from protobuf enum value: SeasonFlavor1Attackers6 = 16;
     */
    SeasonFlavor1Attackers6 = 16,
    /**
     * @generated from protobuf enum value: SeasonFlavor1DefenseFamilyCards = 20;
     */
    SeasonFlavor1DefenseFamilyCards = 20,
    /**
     * @generated from protobuf enum value: SeasonFlavor1Defenders1 = 21;
     */
    SeasonFlavor1Defenders1 = 21,
    /**
     * @generated from protobuf enum value: SeasonFlavor1Defenders2 = 22;
     */
    SeasonFlavor1Defenders2 = 22,
    /**
     * @generated from protobuf enum value: SeasonFlavor1Defenders3 = 23;
     */
    SeasonFlavor1Defenders3 = 23,
    /**
     * @generated from protobuf enum value: SeasonFlavor1Defenders4 = 24;
     */
    SeasonFlavor1Defenders4 = 24,
    /**
     * @generated from protobuf enum value: SeasonFlavor1Defenders5 = 25;
     */
    SeasonFlavor1Defenders5 = 25,
    /**
     * @generated from protobuf enum value: SeasonFlavor1Defenders6 = 26;
     */
    SeasonFlavor1Defenders6 = 26,
    /**
     * @generated from protobuf enum value: SeasonFlavor1MagicFamilyCards = 30;
     */
    SeasonFlavor1MagicFamilyCards = 30,
    /**
     * @generated from protobuf enum value: SeasonFlavor1Magickers1 = 31;
     */
    SeasonFlavor1Magickers1 = 31,
    /**
     * @generated from protobuf enum value: SeasonFlavor1Magickers2 = 32;
     */
    SeasonFlavor1Magickers2 = 32,
    /**
     * @generated from protobuf enum value: SeasonFlavor1Magickers3 = 33;
     */
    SeasonFlavor1Magickers3 = 33,
    /**
     * @generated from protobuf enum value: SeasonFlavor1Magickers4 = 34;
     */
    SeasonFlavor1Magickers4 = 34,
    /**
     * @generated from protobuf enum value: SeasonFlavor1Magickers5 = 35;
     */
    SeasonFlavor1Magickers5 = 35,
    /**
     * @generated from protobuf enum value: SeasonFlavor1Magickers6 = 36;
     */
    SeasonFlavor1Magickers6 = 36
}
