// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "manawave-season-dev-1.proto" (syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum SeasonDev1ClanCardDefs
 */
export enum SeasonDev1ClanCardDefs {
    /**
     * @generated from protobuf enum value: SeasonDev1ClanCard_NotSet = 0;
     */
    SeasonDev1ClanCard_NotSet = 0,
    /**
     * @generated from protobuf enum value: SeasonDev1ClanOfAttack = 1;
     */
    SeasonDev1ClanOfAttack = 1,
    /**
     * @generated from protobuf enum value: SeasonDev1ClanOfDefense = 2;
     */
    SeasonDev1ClanOfDefense = 2,
    /**
     * @generated from protobuf enum value: SeasonDev1ClanOfMagic = 3;
     */
    SeasonDev1ClanOfMagic = 3
}
/**
 * @generated from protobuf enum SeasonDev1TotemDefs
 */
export enum SeasonDev1TotemDefs {
    /**
     * @generated from protobuf enum value: SeasonDev1Totem_NotSet = 0;
     */
    SeasonDev1Totem_NotSet = 0,
    /**
     * @generated from protobuf enum value: SeasonDev1Totem_Attack = 1;
     */
    SeasonDev1Totem_Attack = 1,
    /**
     * @generated from protobuf enum value: SeasonDev1Totem_Defense = 2;
     */
    SeasonDev1Totem_Defense = 2,
    /**
     * @generated from protobuf enum value: SeasonDev1Totem_Magic = 3;
     */
    SeasonDev1Totem_Magic = 3
}
/**
 * @generated from protobuf enum SeasonDev1MonumentCardDefs
 */
export enum SeasonDev1MonumentCardDefs {
    /**
     * @generated from protobuf enum value: SeasonDev1MonumentCard_NotSet = 0;
     */
    SeasonDev1MonumentCard_NotSet = 0,
    /**
     * @generated from protobuf enum value: SeasonDev1MonumentOfAttack = 1;
     */
    SeasonDev1MonumentOfAttack = 1,
    /**
     * @generated from protobuf enum value: SeasonDev1MonumentOfDefense = 2;
     */
    SeasonDev1MonumentOfDefense = 2,
    /**
     * @generated from protobuf enum value: SeasonDev1MonumentOfMagic = 3;
     */
    SeasonDev1MonumentOfMagic = 3,
    /**
     * @generated from protobuf enum value: SeasonDev1MonumentOfAttackAndDefense = 4;
     */
    SeasonDev1MonumentOfAttackAndDefense = 4,
    /**
     * @generated from protobuf enum value: SeasonDev1MonumentOfAttackAndMagic = 5;
     */
    SeasonDev1MonumentOfAttackAndMagic = 5,
    /**
     * @generated from protobuf enum value: SeasonDev1MonumentOfDefenseAndMagic = 6;
     */
    SeasonDev1MonumentOfDefenseAndMagic = 6
}
/**
 * @generated from protobuf enum SeasonDev1FamilyCardDefs
 */
export enum SeasonDev1FamilyCardDefs {
    /**
     * @generated from protobuf enum value: SeasonDev1FamilyCard_NotSet = 0;
     */
    SeasonDev1FamilyCard_NotSet = 0,
    /**
     * @generated from protobuf enum value: SeasonDev1AttackFamilyCards = 10;
     */
    SeasonDev1AttackFamilyCards = 10,
    /**
     * @generated from protobuf enum value: SeasonDev1Attackers1 = 11;
     */
    SeasonDev1Attackers1 = 11,
    /**
     * @generated from protobuf enum value: SeasonDev1Attackers2 = 12;
     */
    SeasonDev1Attackers2 = 12,
    /**
     * @generated from protobuf enum value: SeasonDev1Attackers3 = 13;
     */
    SeasonDev1Attackers3 = 13,
    /**
     * @generated from protobuf enum value: SeasonDev1Attackers4 = 14;
     */
    SeasonDev1Attackers4 = 14,
    /**
     * @generated from protobuf enum value: SeasonDev1Attackers5 = 15;
     */
    SeasonDev1Attackers5 = 15,
    /**
     * @generated from protobuf enum value: SeasonDev1Attackers6 = 16;
     */
    SeasonDev1Attackers6 = 16,
    /**
     * @generated from protobuf enum value: SeasonDev1DefenseFamilyCards = 20;
     */
    SeasonDev1DefenseFamilyCards = 20,
    /**
     * @generated from protobuf enum value: SeasonDev1Defenders1 = 21;
     */
    SeasonDev1Defenders1 = 21,
    /**
     * @generated from protobuf enum value: SeasonDev1Defenders2 = 22;
     */
    SeasonDev1Defenders2 = 22,
    /**
     * @generated from protobuf enum value: SeasonDev1Defenders3 = 23;
     */
    SeasonDev1Defenders3 = 23,
    /**
     * @generated from protobuf enum value: SeasonDev1Defenders4 = 24;
     */
    SeasonDev1Defenders4 = 24,
    /**
     * @generated from protobuf enum value: SeasonDev1Defenders5 = 25;
     */
    SeasonDev1Defenders5 = 25,
    /**
     * @generated from protobuf enum value: SeasonDev1Defenders6 = 26;
     */
    SeasonDev1Defenders6 = 26,
    /**
     * @generated from protobuf enum value: SeasonDev1MagicFamilyCards = 30;
     */
    SeasonDev1MagicFamilyCards = 30,
    /**
     * @generated from protobuf enum value: SeasonDev1Magickers1 = 31;
     */
    SeasonDev1Magickers1 = 31,
    /**
     * @generated from protobuf enum value: SeasonDev1Magickers2 = 32;
     */
    SeasonDev1Magickers2 = 32,
    /**
     * @generated from protobuf enum value: SeasonDev1Magickers3 = 33;
     */
    SeasonDev1Magickers3 = 33,
    /**
     * @generated from protobuf enum value: SeasonDev1Magickers4 = 34;
     */
    SeasonDev1Magickers4 = 34,
    /**
     * @generated from protobuf enum value: SeasonDev1Magickers5 = 35;
     */
    SeasonDev1Magickers5 = 35,
    /**
     * @generated from protobuf enum value: SeasonDev1Magickers6 = 36;
     */
    SeasonDev1Magickers6 = 36
}
