// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "manawave-season-flavor-1.proto" (syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum SeasonFlavor1ClanCardDefs
 */
export enum SeasonFlavor1ClanCardDefs {
    /**
     * @generated from protobuf enum value: SeasonFlavor1ClanCard_NotSet = 0;
     */
    SeasonFlavor1ClanCard_NotSet = 0,
    /**
     * @generated from protobuf enum value: SeasonFlavor1ClanOfAttack = 1;
     */
    SeasonFlavor1ClanOfAttack = 1,
    /**
     * @generated from protobuf enum value: SeasonFlavor1ClanOfDefense = 2;
     */
    SeasonFlavor1ClanOfDefense = 2,
    /**
     * @generated from protobuf enum value: SeasonFlavor1ClanOfMagic = 3;
     */
    SeasonFlavor1ClanOfMagic = 3
}
/**
 * @generated from protobuf enum SeasonFlavor1TotemDefs
 */
export enum SeasonFlavor1TotemDefs {
    /**
     * @generated from protobuf enum value: SeasonFlavor1Totem_NotSet = 0;
     */
    SeasonFlavor1Totem_NotSet = 0,
    /**
     * @generated from protobuf enum value: SeasonFlavor1Totem_Attack = 1;
     */
    SeasonFlavor1Totem_Attack = 1,
    /**
     * @generated from protobuf enum value: SeasonFlavor1Totem_Defense = 2;
     */
    SeasonFlavor1Totem_Defense = 2,
    /**
     * @generated from protobuf enum value: SeasonFlavor1Totem_Magic = 3;
     */
    SeasonFlavor1Totem_Magic = 3
}
/**
 * @generated from protobuf enum SeasonFlavor1MonumentCardDefs
 */
export enum SeasonFlavor1MonumentCardDefs {
    /**
     * @generated from protobuf enum value: SeasonFlavor1MonumentCard_NotSet = 0;
     */
    SeasonFlavor1MonumentCard_NotSet = 0,
    /**
     * @generated from protobuf enum value: ManalithCliffs = 1;
     */
    ManalithCliffs = 1,
    /**
     * @generated from protobuf enum value: JungleOfPyrhhus = 2;
     */
    JungleOfPyrhhus = 2,
    /**
     * @generated from protobuf enum value: RiverOfLyrtif = 3;
     */
    RiverOfLyrtif = 3,
    /**
     * @generated from protobuf enum value: BirthplaceOfGenghis = 4;
     */
    BirthplaceOfGenghis = 4,
    /**
     * @generated from protobuf enum value: TombOfGenghis = 5;
     */
    TombOfGenghis = 5,
    /**
     * @generated from protobuf enum value: GravepitsOfLeruk = 6;
     */
    GravepitsOfLeruk = 6,
    /**
     * @generated from protobuf enum value: FieldsOfLeruk = 7;
     */
    FieldsOfLeruk = 7,
    /**
     * @generated from protobuf enum value: PeaksOfTheoden = 8;
     */
    PeaksOfTheoden = 8,
    /**
     * @generated from protobuf enum value: PlainsOfTheoden = 9;
     */
    PlainsOfTheoden = 9
}
