// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "manawave-season-dev-1.proto" (syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum SeasonDev1ClanCardDefs
 */
export enum SeasonDev1ClanCardDefs {
    /**
     * @generated from protobuf enum value: SeasonDev1ClanCard_NotSet = 0;
     */
    SeasonDev1ClanCard_NotSet = 0,
    /**
     * @generated from protobuf enum value: SeasonDev1ClanOfAttack = 1;
     */
    SeasonDev1ClanOfAttack = 1,
    /**
     * @generated from protobuf enum value: SeasonDev1ClanOfDefense = 2;
     */
    SeasonDev1ClanOfDefense = 2,
    /**
     * @generated from protobuf enum value: SeasonDev1ClanOfMagic = 3;
     */
    SeasonDev1ClanOfMagic = 3
}
/**
 * @generated from protobuf enum SeasonDev1TotemDefs
 */
export enum SeasonDev1TotemDefs {
    /**
     * @generated from protobuf enum value: SeasonDev1Totem_NotSet = 0;
     */
    SeasonDev1Totem_NotSet = 0,
    /**
     * @generated from protobuf enum value: SeasonDev1Totem_Attack = 1;
     */
    SeasonDev1Totem_Attack = 1,
    /**
     * @generated from protobuf enum value: SeasonDev1Totem_Defense = 2;
     */
    SeasonDev1Totem_Defense = 2,
    /**
     * @generated from protobuf enum value: SeasonDev1Totem_Magic = 3;
     */
    SeasonDev1Totem_Magic = 3
}
/**
 * @generated from protobuf enum SeasonDev1MonumentCardDefs
 */
export enum SeasonDev1MonumentCardDefs {
    /**
     * @generated from protobuf enum value: SeasonDev1MonumentCard_NotSet = 0;
     */
    SeasonDev1MonumentCard_NotSet = 0,
    /**
     * @generated from protobuf enum value: SeasonDev1MonumentOfAttack = 1;
     */
    SeasonDev1MonumentOfAttack = 1,
    /**
     * @generated from protobuf enum value: SeasonDev1MonumentOfDefense = 2;
     */
    SeasonDev1MonumentOfDefense = 2,
    /**
     * @generated from protobuf enum value: SeasonDev1MonumentOfMagic = 3;
     */
    SeasonDev1MonumentOfMagic = 3,
    /**
     * @generated from protobuf enum value: SeasonDev1MonumentOfAttackAndDefense = 4;
     */
    SeasonDev1MonumentOfAttackAndDefense = 4,
    /**
     * @generated from protobuf enum value: SeasonDev1MonumentOfAttackAndMagic = 5;
     */
    SeasonDev1MonumentOfAttackAndMagic = 5,
    /**
     * @generated from protobuf enum value: SeasonDev1MonumentOfDefenseAndMagic = 6;
     */
    SeasonDev1MonumentOfDefenseAndMagic = 6,
    /**
     * @generated from protobuf enum value: SeasonDev1Monument_OptPlayerWins = 7;
     */
    SeasonDev1Monument_OptPlayerWins = 7,
    /**
     * @generated from protobuf enum value: SeasonDev1Monument_OsbPlayerWins = 8;
     */
    SeasonDev1Monument_OsbPlayerWins = 8,
    /**
     * @generated from protobuf enum value: SeasonDev1Monument_BothPlayersLose = 9;
     */
    SeasonDev1Monument_BothPlayersLose = 9,
    /**
     * @generated from protobuf enum value: SeasonDev1Monument_BothPlayersWin = 10;
     */
    SeasonDev1Monument_BothPlayersWin = 10,
    /**
     * @generated from protobuf enum value: SeasonDev1Monument_ForcedDraw = 11;
     */
    SeasonDev1Monument_ForcedDraw = 11
}
