// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "manawave-season-zero-1.proto" (syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum ClanCardDefs
 */
export enum ClanCardDefs {
    /**
     * @generated from protobuf enum value: ClanCard_NotSet = 0;
     */
    ClanCard_NotSet = 0,
    /**
     * @generated from protobuf enum value: ClanOfSacrifice = 1;
     */
    ClanOfSacrifice = 1,
    /**
     * @generated from protobuf enum value: ClanOfLife = 2;
     */
    ClanOfLife = 2,
    /**
     * @generated from protobuf enum value: ClanOfDiversity = 3;
     */
    ClanOfDiversity = 3
}
/**
 * @generated from protobuf enum TotemDefs
 */
export enum TotemDefs {
    /**
     * @generated from protobuf enum value: Totem_NotSet = 0;
     */
    Totem_NotSet = 0,
    /**
     * @generated from protobuf enum value: Totem_Ox = 1;
     */
    Totem_Ox = 1,
    /**
     * @generated from protobuf enum value: Totem_Spirits = 2;
     */
    Totem_Spirits = 2,
    /**
     * @generated from protobuf enum value: Totem_Tiger = 3;
     */
    Totem_Tiger = 3
}
/**
 * @generated from protobuf enum MonumentCardDefs
 */
export enum MonumentCardDefs {
    /**
     * @generated from protobuf enum value: MonumentCard_NotSet = 0;
     */
    MonumentCard_NotSet = 0,
    /**
     * @generated from protobuf enum value: MonumentOfLife = 1;
     */
    MonumentOfLife = 1,
    /**
     * @generated from protobuf enum value: MonumentOfSacrifice = 2;
     */
    MonumentOfSacrifice = 2,
    /**
     * @generated from protobuf enum value: MonumentOfDiversty = 3;
     */
    MonumentOfDiversty = 3,
    /**
     * @generated from protobuf enum value: MonumentOfJustice = 4;
     */
    MonumentOfJustice = 4,
    /**
     * @generated from protobuf enum value: MonumentOfTranquility = 5;
     */
    MonumentOfTranquility = 5,
    /**
     * @generated from protobuf enum value: MonumentOfMagic = 6;
     */
    MonumentOfMagic = 6,
    /**
     * @generated from protobuf enum value: MonumentOfNature = 7;
     */
    MonumentOfNature = 7,
    /**
     * @generated from protobuf enum value: MonumentOfWar = 8;
     */
    MonumentOfWar = 8,
    /**
     * @generated from protobuf enum value: MonumentOfPeace = 9;
     */
    MonumentOfPeace = 9
}
/**
 * @generated from protobuf enum FamilyCardDefs
 */
export enum FamilyCardDefs {
    /**
     * @generated from protobuf enum value: FamilyCard_NotSet = 0;
     */
    FamilyCard_NotSet = 0,
    /**
     * @generated from protobuf enum value: OxFamilyCards = 10;
     */
    OxFamilyCards = 10,
    /**
     * @generated from protobuf enum value: MwForestHunters = 11;
     */
    MwForestHunters = 11,
    /**
     * @generated from protobuf enum value: GrasslandShepherds = 12;
     */
    GrasslandShepherds = 12,
    /**
     * @generated from protobuf enum value: RuggedShepherds = 13;
     */
    RuggedShepherds = 13,
    /**
     * @generated from protobuf enum value: Farmers = 14;
     */
    Farmers = 14,
    /**
     * @generated from protobuf enum value: MysticFarmers = 15;
     */
    MysticFarmers = 15,
    /**
     * @generated from protobuf enum value: SoylentGreenFarmers = 16;
     */
    SoylentGreenFarmers = 16,
    /**
     * @generated from protobuf enum value: SpiritsFamilyCards = 20;
     */
    SpiritsFamilyCards = 20,
    /**
     * @generated from protobuf enum value: RoadBuilders = 21;
     */
    RoadBuilders = 21,
    /**
     * @generated from protobuf enum value: ManaChannelers = 22;
     */
    ManaChannelers = 22,
    /**
     * @generated from protobuf enum value: Enchanters = 23;
     */
    Enchanters = 23,
    /**
     * @generated from protobuf enum value: Channelers = 24;
     */
    Channelers = 24,
    /**
     * @generated from protobuf enum value: Wizards = 25;
     */
    Wizards = 25,
    /**
     * @generated from protobuf enum value: Sacrificers = 26;
     */
    Sacrificers = 26,
    /**
     * @generated from protobuf enum value: TigerFamilyCards = 30;
     */
    TigerFamilyCards = 30,
    /**
     * @generated from protobuf enum value: ClubWielders = 31;
     */
    ClubWielders = 31,
    /**
     * @generated from protobuf enum value: ShieldCrafters = 32;
     */
    ShieldCrafters = 32,
    /**
     * @generated from protobuf enum value: Templars = 33;
     */
    Templars = 33,
    /**
     * @generated from protobuf enum value: Defenders = 34;
     */
    Defenders = 34,
    /**
     * @generated from protobuf enum value: Martyrs = 35;
     */
    Martyrs = 35,
    /**
     * @generated from protobuf enum value: Slavers = 36;
     */
    Slavers = 36
}
