
export type PlayerId = 'PlayerA' | 'Player1'
export type CardDecoration = 'mw-icon-black-side-up' | 'mw-icon-white-side-up'


export const HEX_COLOR_CODE_MANALITH_TOKEN = "#0827F5"
export const HEX_COLOR_CODE_POPULATION_TOKEN = "#00873E"
export const HEX_COLOR_CODE_SOULSTAIN_TOKEN = "#000000"

export const HEX_COLOR_CODE_ATTACK_COUNTER = "#E10600"
export const HEX_COLOR_CODE_SHIELD_COUNTER = "#FF8200"
export const HEX_COLOR_CODE_MANA_COUNTER = "#C5B4E3"
export const HEX_COLOR_CODE_MANALITH_CLAIM_COUNTER = "#A4DBE8"
export const HEX_COLOR_CODE_POPULATION_INCREASE_COUNTER = "#26D07C"
export const HEX_COLOR_CODE_POPULATION_SACRIFICE_COUNTER = "#651C32"

export const HEX_COLOR_CODE_MANAWAVE_ROUND_TOKEN = "#AC4FC6"


export const HEX_COLOR_CODE_MANALITH_TOKEN_TEXT = "#FFFFFF"
export const HEX_COLOR_CODE_POPULATION_TOKEN_TEXT = "#FFFFFF"
export const HEX_COLOR_CODE_SOULSTAIN_TOKEN_TEXT = "#FFFFFF"

export const HEX_COLOR_CODE_ATTACK_COUNTER_TEXT = "#FFFFFF"
export const HEX_COLOR_CODE_SHIELD_COUNTER_TEXT = "#000000"
export const HEX_COLOR_CODE_MANA_COUNTER_TEXT = "#000000"
export const HEX_COLOR_CODE_MANALITH_CLAIM_COUNTER_TEXT = "#000000"
export const HEX_COLOR_CODE_POPULATION_INCREASE_COUNTER_TEXT = "#000000"
export const HEX_COLOR_CODE_POPULATION_SACRIFICE_COUNTER_TEXT = "#FFFFFF"

export const HEX_COLOR_CODE_MANAWAVE_ROUND_TOKEN_TEXT = "#FFFFFF"


export const MODE_PRINT_SETTINGS_DEFAULT_FONT_SIZE = 16;
export const MODE_PRINT_SETTINGS_DEFAULT_IMAGE_SIZE = 14;

export const MODE_DIGITAL_SETTINGS_DEFAULT_FONT_SIZE = 16;
export const MODE_DIGITAL_SETTINGS_DEFAULT_IMAGE_SIZE = 14;


export const MW_DOC_SITE_PREFIX = "http://localhost:3000";
